### ISSUE TITLE
getStorage('view_mode') in token_install() gives "entity type does not exist"

### ISSUE THREAD

**Issue by arildm** [larowlan/token#28]
Enabling token on current 8.x core, I get:

```
The "view_mode" entity type does not exist.
```

**Comment by Berdir** [comment]
That has been renamed to entity_view_mode/entity_form_mode, should be easy to fix.

**Comment by Berdir** [comment]
The code is currently adding a token view_mode to all entity types. Maybe @davereid can shed some light on what that is exactly used for? With a view_mode UI in core, maybe we can let the user manage this and decide which view mode to use for something and use the default if nothing is defined? Or are we using this to display single fields with that view mode, so that users have a place to configure that?

The current implementation has the problem that it only works for entity types that exist on the system when token is installed, not for those from modules enabled later on (or even harder, existing modules having new entity types).

**Comment by davereid** [comment]
Yes this is something I'm _not_ happy about in Drupal 8, the inability to define view modes no matter if the entity type is available or not. I don't want to have to have users go fill out a new View mode form and have to make sure they typed everything correctly so things will magically work, I just want it to be available and work out of the box.
